### ISSUE TITLE
I think this is awesome, is it abandoned?

### ISSUE THREAD

**Issue by xplshn** [Geronymos/desktop-icons#14]

**Comment by Geronymos** [comment]
I use the desktop-icons daily to show important shortcuts. Besides that, I don't need any new feature. I still welcome any additions people make. But for me this project is finished till I find a need for a new feature. 

Maybe when I get bored I might rewrite this in gtk4 (I somehow missed [gtk4-layer-shell](https://github.com/wmww/gtk4-layer-shell) when I started this project). This might make it more future proof. 

The original idea for writing it in C was to make it minimalist. But another direction I was thinking was to use this application to test out GTK Rust bindings and try out [Relm4](https://relm4.org/). 

Would be interesting though to maybe really finish this and publish it.

**Comment by xplshn** [comment]
Okay! Thanks. I will rewrite this in Go soon, because I want to add a menu that relies on `plumb` from plan9port. Thanks for the info & excellent start-point!

**Comment by xplshn** [comment]
Sorry to keep bothering. I just forked this, would you be so kind as to allow me to relicense this into 3BSD or MIT? I plan to implement the missing functionality :)

**Comment by Geronymos** [comment]
No

**Comment by xplshn** [comment]
I'm writing one in Go right now, it'll be easier for me to integrate with my executable format (.AppBundles, and the PELFd daemon). Anyways. COol project. Thanks for answering

**Comment by Geronymos** [comment]
I will watch your project with great interest.

**Comment by xplshn** [comment]
This is the result of 40 minutes of fiddling with the GTK3 bindings for Go, maybe I can get it to have the same functionality as `dicons.c` in a few hours.
![image](https://github.com/user-attachments/assets/c2c173c3-9e59-4b17-9328-41341a105cd2)
